apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: fruit_management
  name: fruit_management-build
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 1234-fruit_management:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: java:11
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
