apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-dev
spec:
  params:
  - name: GUID
    type: string
    description: GUID for unique user
  tasks:
  - name: clone-gitea-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: https://homework-gitea.apps.shared.na.openshift.opentlc.com/bgottfri-redhat.com/ocp4_app_deploy_homework.git
      - name: deleteExisting
        value: "true"
      - name: revision
        value: pipelines
    workspaces:
      - name: output
        workspace: source
  - name: patch-pom
    taskRef:
      name: bash
    runAfter:
    - clone-gitea-repo
    params:
      - name: ARGS
        value: sed -i 's/GUID/$(params.GUID)/g' openshift-tasks/pom.xml
    workspaces:
      - name: workspace
        workspace: source
  - name: mvn-build
    taskRef:
      name: maven
      kind: ClusterTask
    runAfter:
    - patch-pom
    params:
      - name: GOALS
        value: 
        - "clean"
        - "package"
        - "-DskipTests=true"
    workspaces:
      - name: source
        workspace: source
      - name: maven-settings
        workspace: maven-settings
  workspaces:
    - name: source
    - name: maven-settings 
