apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cleanup-fm
spec:
  params:
  - name: GUID
    type: string
    description: GUID for unique user
  tasks:
  - name: clean-up-fruit-management-dev-app
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete all -n $(params.GUID)-fruit-management-dev -l app=tasks
  - name: clean-up-fruit-management-dev-build
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete all -n $(params.GUID)-fruit-management-dev -l build=tasks
  - name: clean-up-fruit-management-dev-taskbuild
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete all -n $(params.GUID)-fruit-management-dev -l build=tasks
  - name: clean-up-fruit-management-dev-cm
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete cm -n $(params.GUID)-fruit-management-dev tasks-config
  - name: clean-up-nexus-settings-cm
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete cm -n $(params.GUID)-fruit-management-dev nexus-settings
  - name: clean-up-fruit-management-blue
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete all -n $(params.GUID)-fruit-management-prod -l app=tasks-blue
  - name: clean-up-fruit-management-green
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete all -n $(params.GUID)-fruit-management-prod -l app=tasks-green
  - name: clean-up-blue-fruit-management-cm
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete cm -n $(params.GUID)-fruit-management-prod tasks-blue-config
  - name: clean-up-green-fruit-management-cm
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete cm -n $(params.GUID)-fruit-management-prod tasks-green-config
  - name: clean-up-fruit-management-route
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete route -n $(params.GUID)-fruit-management-prod tasks