apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dev-deploy
spec:
  params:
  - name: GUID
    type: string
    description: GUID for unique user
  tasks:
  - name: clone-gitea-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
      - name: url
        value: https://homework-gitea.apps.shared.na.openshift.opentlc.com/bgottfri-redhat.com/ocp4_app_deploy_homework.git
      - name: deleteExisting
        value: "true"
      - name: revision
        value: pipelines
      - name: sslVerify
        value: "false"
    workspaces:
      - name: output
        workspace: source
  - name: dev-deploy-patch-dc
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc patch -n $(params.GUID)-tasks-dev dc tasks -p '{"spec":{"template":{"spec":{"containers":[{"name":"tasks","image":"image-registry.openshift-image-registry.svc:5000/$(params.GUID)-tasks-dev/$(params.GUID)-tasks:latest"}]}}}}'
    runAfter:
    - clone-gitea-repo
  - name: dev-deploy-delete-cm
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: SCRIPT
        value: oc delete cm -n $(params.GUID)-tasks-dev tasks-config
    runAfter:
    - dev-deploy-patch-dc
  - name: dev-deploy-recreate-cm
    taskRef:
      name: openshift-client-workspace
      kind: Task
    params:
      - name: ARGS
        value:
          - create
          - configmap
          - -n $(params.GUID)-tasks-dev tasks-config
          - --from-file=openshift-tasks/configuration/application-users.properties 
          - --from-file=openshift-tasks/configuration/application-roles.properties
    runAfter:
    - dev-deploy-delete-cm
    workspaces:
      - name: workspace
        workspace: source
  - name: dev-deploy-rollout
    taskRef:
      name: openshift-client
      kind: ClusterTask
    params:
      - name: ARGS
        value:
          - rollout
          - latest
          - -n $(params.GUID)-tasks-dev tasks
    runAfter:
    - dev-deploy-recreate-cm
  - name: dev-wait-for-rollout
    taskRef:
      name: wait-for-rollout
      kind: Task
    params:
      - name: namespace
        value: $(params.GUID)-tasks-dev
      - name: dc-name
        value: tasks
      - name: rc-name
        value: tasks
    runAfter:
    - dev-deploy-rollout
  workspaces:
    - name: source