apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: 1234-setup
spec:
  resources:
  - name: gitea-repo
    type: git
  params:
  - name: GUID
    type: string
    description: GUID for unique user
  tasks:
  - name: apply-dev-manifests
    taskRef:
      name: apply-manifests-namespace
    resources:
      inputs:
      - name: source
        resource: gitea-repo
    params:
      - name: manifest_dir
        value: pipelines_implementation/manifests/tasks-dev
      - name: namespace
        value: $(params.GUID)-dev