apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: apply-manifests-namespace
spec:
  params:
  - default: k8s
    description: The directory in source that contains yaml manifests
    name: manifest_dir
    type: string
  - default: default
    description: The namespace to apply the manifests within
    name: namespace
    type: string
  steps:
  - args:
    - |-
      echo Applying manifests in $(params.manifest_dir) directory to namespace $(params.namespace)
      oc apply -f $(params.manifest_dir) -n $(params.namespace)
      echo -----------------------------------
    command:
    - /bin/bash
    - -c
    image: quay.io/openshift/origin-cli:latest
    name: apply
    resources: {}
    workingDir: /source
  workspaces:
  - name: source
    mountPath: /source