apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: bash
spec:
  params:
  - description: Bash arguments to run
    name: ARGS
    type: string
  steps:
  - args:
    - |-
      $(params.ARGS)
    command:
    - /bin/bash
    - -c
    image: registry.redhat.io/ubi8/ubi:latest
    name: bash
    workingDir: /workspace/workspace
  workspaces:
  - name: workspace