apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: skopeo
spec:
  params:
  - name: ARGS
    description: The skopeo CLI arguments to run
    default: --help
  steps:
  - name: skopeo
    image: quay.io/vinamra2807/skopeo:latest
    script: |
      skopeo $(params.ARGS)