apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: store-variable
  annotations:
    description: |
      Store a bash command into a Result file that can be retrieved by a later Task
spec:
  params:
  - description: Bash command to create variable value
    name: script
    type: string
  steps:
  - args:
    - |-
      $(params.script) | tr -d "\n" | tee $(results.variable.path)
    command:
    - /bin/bash
    - -c
    image: registry.redhat.io/ubi8/ubi:latest
    name: bash
    workingDir: /workspace/workspace
  results:
    - name: variable
      description: Variable being stored
  workspaces:
  - name: workspace