apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: tasks
  name: taskbuild
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 1234-tasks:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: jboss-eap71-openshift:1.4
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: 27x1rbNCZ8a2Q1rpdm8S
    type: GitHub
  - generic:
      secret: HPrrMhjVFNP_jd27rR51
    type: Generic
